### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by ababra** [jshimko/meteor-autoform-selectize#5]
Does this package support HTML formatting for the list items? I tried the following code, however the tags do not get formatted:

```
    order_tests: {
        type: [String],
        autoform: {
            type: 'selectize',
            placeholder: 'Click here to add tests...',
            multiple: true,
            label: false,
            options: function() {
                return _.map(tests.find({}, {sort: {test_name: 1}}).fetch(), function(item) {
                    return {value: item._id, label: function(){
                            return '<h1>' + item.test_name + '</h1> - Free'
                        }
                    }}
                })
            },
            selectizeOptions: {
                plugins: ['remove_button']
            }
        }
    }
```

**Comment by jshimko** [comment]
That's really an Autoform thing, not this plugin.  The options key appears to only allow an object with string values.  (https://github.com/aldeed/meteor-autoform#affieldinput)

I suppose there's probably a way to make your own input type that doesn't escape the html, but that sounds like more work than necessary.  Since you appear to just be trying to style the items a little differently with h1 tags, it'd probably be easier to just grab those option items with jQuery and add the styling you want.  The input has a class of `.selectize-input` and the selected items have an `.item` class.

So you could...

``` js
Template.myTemplate.onRendered(function() {
  $('.selectize-input .item').css('WHATEVER');
});
```
